# Generated by Django 3.2.8 on 2021-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
